name: Any Branch PR Test Workflow

on: [push]
jobs:
  job_1:
    name: Build and Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.16.0]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout PR branch branch
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM install
        run: |
          npm install
        env:
          CI: true